CREATE TABLE blogful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    date modified TIMESTAMP DEFAULT no() NOT NULL,
    folder_id INTEGER
        REFERENCES blogful_folders(id) ON DELETE CACADE NOT NULL,
    content TEXT
);